[package]
name = "kast"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.3"
egui = "0.33.3"
winit = { version = "0.30.12", features = ["x11"] }
serde = {version = "1", features = ["derive"]}
toml = "0.9.10"
home = "0.5.12"

